[package]
name = "portforwarder"
version = "0.1.0"
authors = ["Thomas Kühnel <kuehnelth@gmail.com>"]
edition = "2018"

[dependencies]
mio = "0.6"
multi-map = "1.2.0"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1